config/routes.rb
Associations::Application.routes.draw do
    resources :receipts

    resources :entradas

    resources :payments

    resources :expenses

    root  'customers#index'

    resources :orders do
        resources :receipts, shallow: true
    end

    resources :line_items do
        get :autocomplete_product_code, :on => :collection
    end

    resources :customers do
        resources :orders, shallow: true
    end
    resources :customers, shallow: true do
        resources :orders do
            resources :line_items, only: [:new, :create, :edit, :update, :destroy, :autocomplete]
        end
    end

    resources :users
    resources :products, controllers: {line_item: 'line_item'}
    resources :sessions, only: [:new, :create, :destroy]
    resources :orders

    get '/signin' => 'sessions#new'
    delete '/signout' => 'sessions#destroy'

    get 'info' => "orders#info", :as => :order_info

end

app/models/customer.rb
class Customer < ActiveRecord::Base
	has_many :orders, dependent: :destroy
	
	# Validations
	#validates :name, presence:  {message: "Você precisa preencher esse campo."}, length: { maximum: 40 }
	#validates :street, length: { maximum: 99 }
	#validates :city, presence:  {message: "Você precisa preencher esse campo."}, length: { maximum: 30 }
	#validates :state, presence:  {message: "Você precisa preencher esse campo."}, length: { maximum: 20 }
	#validates :rg, presence: {message: "Você precisa preencher esse campo."}, uniqueness: {message: "RG informado já está cadastrado."}
	#validates :cpf, presence: {message: "Você precisa preencher esse campo."}, uniqueness: {message: "CPF informado já está cadastrado."}
	#validates :name_mother, presence: {message: "Você precisa preencher esse campo."}, length: {maximum: 50}
	#validates :zipcode, length: { maximum: 9 }
	#validates :cellphone, presence: {message: "Você precisa prencher esse campo."}
	


 def self.search(query)
        where("LOWER(name) like ?", "%#{query}%") 
    end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
	before_action :find_customer, only: [:show, :edit, :update]

	def index
		if params[:search]
            @customers = Customer.search(params[:search]).order("name ASC")
        else
            @customers = Customer.all.order('name ASC')
        end
	end

	def show
	end

	def new
		@customer = Customer.new
	end

	def create
		@customer = Customer.new(customer_params)
		if @customer.save
			flash[:success] = "Cliente adicionado com sucesso!"
			redirect_to @customer
		else
			render "new"
		end
	end

	def edit
	end

	def update
		if @customer.update_attributes(customer_params)
			flash[:success] = "Cliente alterado com sucesso!"
			redirect_to @customer
		else
			render "edit"
		end
	end

	def destroy
		Customer.find(params[:id]).destroy
		flash[:success] = "Cliente excluído com sucesso!"
		redirect_to customers_path
	end
	
	private
		def customer_params
			params.require(:customer).permit(:name, :street, :city, :state, :zipcode, :homephone, :cellphone, :email, :cpf, :name_mother, :rg)
		end

		def find_customer
			@customer = Customer.find(params[:id])
		end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_customer_form.html.erb
<%= form_for customer, html: {class: "form-horizontal"} do |f| %>
<%#= render "shared/error_messages", object: f.object %>

	<div class="form-group">
			<label class="col-md-2 control-label" for="customer_name">NOME:</label>
					<div class="col-md-5">
							<%= f.text_field :name, class: "form-control" %>
</div>
<%= render partial: "shared/validation_error_message_first",
						locals: { err_msgs: customer.errors[:name], attr_name: "Nome" }%>
</div>
<div class="form-group">
	<label class="col-md-2 control-label" for="customer_cpf">CPF:</label>
	<div class="col-md-5">
		<%= f.text_field :cpf, class: "form-control" %>
	</div>
	<%= render partial: "shared/validation_error_message_first",
						locals: { err_msgs: customer.errors[:cpf], attr_name: "Cpf" }%>
</div>
<div class="form-group">
	<label class="col-md-2 control-label" for="customer_rg">RG:</label>
	<div class="col-md-5">
		<%= f.text_field :rg, class: "form-control" %>
	</div>
	<%= render partial: "shared/validation_error_message_first",
						locals: { err_msgs: customer.errors[:rg], attr_name: "Rg" }%>
</div>
<div class="form-group">
	<label class="col-md-2 control-label" for="customer_name_mother">NOME DA MÃE:</label>
	<div class="col-md-5">
		<%= f.text_field :name_mother, class: "form-control" %>
	</div>
	<%= render partial: "shared/validation_error_message_first",
						locals: { err_msgs: customer.errors[:name_mother], attr_name: "Nome da mãe" }%>
</div>
<div class="form-group">
	<label class="col-md-2 control-label" for="customer_street">RUA:</label>
	<div class="col-md-5">
		<%= f.text_field :street, class: "form-control" %>
	</div>
	<%= render partial: "shared/validation_error_message_first",
						locals: { err_msgs: customer.errors[:street], attr_name: "Rua" }%>
</div>
<div class="form-group">
	<label class="col-md-2 control-label" for="customer_city">CIDADE:</label>
	<div class="col-md-5">
		<%= f.text_field :city, class: "form-control" %>
	</div>
	<%= render partial: "shared/validation_error_message_first",
						locals: { err_msgs: customer.errors[:city], attr_name: "Cidade" }%>
</div>
<div class="form-group">
	<label class="col-md-2 control-label" for="customer_state">ESTADO:</label>
	<div class="col-md-5">
		<%= f.select :state, options_for_select(us_states, customer[:state]), {}, class: "form-control" %>
	</div>
	<%= render partial: "shared/validation_error_message_first",
						locals: { err_msgs: customer.errors[:state], attr_name: "Estado" }%>
</div>
<div class="form-group">
	<label class="col-md-2 control-label" for="customer_zipcode">CEP:</label>
	<div class="col-md-5">
		<%= f.text_field :zipcode, class: "form-control", placeholder: "#####-###" %>
	</div>
	<%= render partial: "shared/validation_error_message_first",
						locals: { err_msgs: customer.errors[:zipcode], attr_name: "CEP" }%>
</div>

<div class="form-group">
	<label class="col-md-2 control-label" for="customer_homephone">TELEFONE:</label>
	<div class="col-md-5">
		<%= f.telephone_field :homephone, class: "form-control", placeholder: "##-####-####" %>
	</div>
	<%= render partial: "shared/validation_error_message_first",
						locals: { err_msgs: customer.errors[:homephone], attr_name: "Telefone Principal" }%>
</div>
<div class="form-group">
	<label class="col-md-2 control-label" for="customer_cellphone">CELULAR:</label>
	<div class="col-md-5">
		<%= f.telephone_field :cellphone, class: "form-control", placeholder: "##-####-####" %>
	</div>
	<%= render partial: "shared/validation_error_message_first",
						locals: { err_msgs: customer.errors[:cellphone], attr_name: "Telefone Opcional" }%>
</div>
<div class="form-group">
	<label class="col-md-2 control-label" for="customer_email">E-MAIL:</label>
	<div class="col-md-5">
		<%= f.email_field :email, class: "form-control" %>
	</div>
	<%= render partial: "shared/validation_error_message_first",
						locals: { err_msgs: customer.errors[:email], attr_name: "Email" }%>
</div>
<div style="margin-left: 45%">
	<%= f.submit "Salvar", class: "btn btn-success" %>

	<%= link_to "Voltar", customers_path, class: "btn btn-default" %>
	<br><br><br>
</div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editar Cliente</h1>
<%= render partial: "customer_form", locals: {customer: @customer} %>

app/views/customers/index.html.erb
<h1>Clientes</h1>

<div class="row">
	<div class="col-md-12">
		<%= link_to " Adicionar Cliente", new_customer_path, class: "btn btn-success valign_middle glyphicon glyphicon-plus pull-right" %>
	
		<%= form_tag(customers_path, :method => "get", :class => "form-inline pull-right", id: "search-form", style: "margin-right: 2%") do %>
		<%= text_field_tag :search, params[:search], placeholder: "Buscar Cliente", class: "form-control" %>
		<%= button_tag "", :name => nil, class: "btn btn-default glyphicon glyphicon-search" %>
		<% end %>

	</div>

</div>

<table class="table table-striped table-hover">
	<thead>
		<tr>
			<th>NOME</th>
			<th>E-MAIL</th>
			<th></th>
			<th></th>
			<th></th>
		</tr>
	</thead>

	<tbody>
		<% @customers.each do |customer| %>
		<tr>
			<td><%= customer.name %></td>
			<td><%= customer.email %></td>
			<td><%= link_to "Detalhes do cliente e ordens", customer, :class => "btn btn-primary btn-xs" %></td>
			<td><%= link_to "Editar", edit_customer_path(customer), :class => "btn btn-warning btn-xs" %></td>
			<td><%= link_to "Excluir", customer, method: :delete,
	data: { confirm: "Tem certeza que deseja excluir o cliente?" }, :class => "btn btn-danger btn-xs" %></td>
		</tr>
		<% end %>
	</tbody>
</table>


	

app/views/customers/new.html.erb
<h1>Novo Cliente</h1>
<%= render partial: "customer_form", locals: {customer: @customer} %>

app/views/customers/show.html.erb
<div class="row">
    <div class="col-md-6">
        <h1>Cliente</h1>
        <%= link_to "Voltar", customers_path, class: "btn btn-default pull-right" %>
        <%= link_to "Editar", edit_customer_path(@customer), class: "btn btn-warning pull-right" %> 

        <br>
        <br>
        <br>

        <table class="table table-striped table-hover">
            <tr>
                <td class="field-label col-md-2 active text-right"><label>NOME:</label></td>
                <td class="col-md-4"><%= @customer.name %></td>
            </tr>
            <tr>
                <td class="field-label col-md-2 active text-right"><label>CPF:</label></td>
                <td class="col-md-4"><%= @customer.cpf %></td>
            </tr>
            <tr>
                <td class="field-label col-md-2 active text-right"><label>RG:</label></td>
                <td class="col-md-4"><%= @customer.rg %></td>
            </tr>
            <tr>
                <td class="field-label col-md-2 active text-right"><label>NOME DA MÃE:</label></td>
                <td class="col-md-4"><%= @customer.name_mother %></td>
            </tr>
            <tr>
                <td class="field-label col-md-2 active text-right"><label>TELEFONE PRINCIPAL:</label></td>
                <td class="col-md-4"><%= @customer.homephone %></td>
            </tr>
            <tr>
                <td class="field-label col-md-2 active text-right"><label>TELEFONE CELULAR:</label></td>
                <td class="col-md-4"><%= @customer.cellphone %></td>
            </tr>
            <tr>
                <td class="field-label col-md-2 active text-right"><label>RUA:</label></td>
                <td class="col-md-4"><%= @customer.street %></td>
            </tr>
            <tr>
                <td class="field-label col-md-2 active text-right"><label>CIDADE:</label></td>
                <td class="col-md-4"><%= @customer.city %></td>
            </tr>
            <tr>
                <td class="field-label col-md-2 active text-right"><label>ESTATO:</label></td>
                <td class="col-md-4"><%= @customer.state %></td>
            </tr>
            <tr>
                <td class="field-label col-md-2 active text-right"><label>CEP:</label></td>
                <td class="col-md-4"><%= @customer.zipcode %></td>
            </tr>


            <tr>
                <td class="field-label col-md-2 active text-right"><label>E-MAIL:</label></td>
                <td class="col-md-4"><%= @customer.email %></td>
            </tr>
        </table>
    </div>
    <div class="col-md-6">
        <h1>Ordens</h1>
        <%= link_to "Adicionar Ordem", new_customer_order_path(@customer), class: "btn btn-success valign_middle" %>
        <br />
        <br />


        <table class="table table-striped table-hover">
            <thead>
                <tr>

                    <th>DATA</th>
                    <th></th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <% @customer.orders.each do |order| %>
                <tr>
                    <td><%= order.date.try(:strftime, "%-d/%-m/%Y") %></td>
                    <td><%= link_to "Ver", order, :class => "btn btn-primary btn-xs" %></td>
                    <td><%= link_to "Editar", edit_order_path(order), :class => "btn btn-warning btn-xs" %></td>
                    <td><%= link_to "Excluir", order, :class => "btn btn-danger btn-xs", method: :delete, data: { confirm: "Tem certeza que quer excluir a ordem?" } %></td>
                </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</div>	<!-- .row -->

<br>



<!--		<nav>
<ul class="pagination">

<%#= will_paginate @customer.orders = Order.paginate(:page => params[:page], :per_page => 15), renderer: BootstrapPagination::Rails %>
</ul>
    </nav>-->