config/routes.rb
Associations::Application.routes.draw do
    resources :receipts

    resources :entradas

    resources :payments

    resources :expenses

    root  'customers#index'

    resources :orders do
        resources :receipts, shallow: true
    end

    resources :line_items do
        get :autocomplete_product_code, :on => :collection
    end

    resources :customers do
        resources :orders, shallow: true
    end
    resources :customers, shallow: true do
        resources :orders do
            resources :line_items, only: [:new, :create, :edit, :update, :destroy, :autocomplete]
        end
    end

    resources :users
    resources :products, controllers: {line_item: 'line_item'}
    resources :sessions, only: [:new, :create, :destroy]
    resources :orders

    get '/signin' => 'sessions#new'
    delete '/signout' => 'sessions#destroy'

    get 'info' => "orders#info", :as => :order_info

end

app/models/entrada.rb
class Entrada < ActiveRecord::Base
    belongs_to :order
end

app/controllers/entradas_controller.rb
class EntradasController < ApplicationController
  before_action :set_entrada, only: [:show, :edit, :update, :destroy]

  # GET /entradas
  # GET /entradas.json
  def index
    @entradas = Entrada.all
  end

  # GET /entradas/1
  # GET /entradas/1.json
  def show
  end

  # GET /entradas/new
  def new
    @entrada = Entrada.new
  end

  # GET /entradas/1/edit
  def edit
  end

  # POST /entradas
  # POST /entradas.json
  def create
    @entrada = Entrada.new(entrada_params)

    respond_to do |format|
      if @entrada.save
        format.html { redirect_to @entrada, notice: 'Entrada was successfully created.' }
        format.json { render action: 'show', status: :created, location: @entrada }
      else
        format.html { render action: 'new' }
        format.json { render json: @entrada.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entradas/1
  # PATCH/PUT /entradas/1.json
  def update
    respond_to do |format|
      if @entrada.update(entrada_params)
        format.html { redirect_to @entrada, notice: 'Entrada was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @entrada.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entradas/1
  # DELETE /entradas/1.json
  def destroy
    @entrada.destroy
    respond_to do |format|
      format.html { redirect_to entradas_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entrada
      @entrada = Entrada.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entrada_params
      params.require(:entrada).permit(:value)
    end
end

app/helpers/entradas_helper.rb
module EntradasHelper
end

app/views/entradas/_form.html.erb
<%= form_for(@entrada) do |f| %>
  <% if @entrada.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entrada.errors.count, "error") %> prohibited this entrada from being saved:</h2>

      <ul>
      <% @entrada.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :value %><br>
    <%= f.text_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entradas/edit.html.erb
<h1>Editing entrada</h1>

<%= render 'form' %>

<%= link_to 'Show', @entrada %> |
<%= link_to 'Back', entradas_path %>

app/views/entradas/index.html.erb
<h1>Listing entradas</h1>

<table>
  <thead>
    <tr>
      <th>Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @entradas.each do |entrada| %>
      <tr>
        <td><%= entrada.value %></td>
        <td><%= link_to 'Show', entrada %></td>
        <td><%= link_to 'Edit', edit_entrada_path(entrada) %></td>
        <td><%= link_to 'Destroy', entrada, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Entrada', new_entrada_path %>

app/views/entradas/new.html.erb
<h1>New entrada</h1>

<%= render 'form' %>

<%= link_to 'Back', entradas_path %>

app/views/entradas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Value:</strong>
  <%= @entrada.value %>
</p>

<%= link_to 'Edit', edit_entrada_path(@entrada) %> |
<%= link_to 'Back', entradas_path %>