config/routes.rb
Associations::Application.routes.draw do
    resources :receipts

    resources :entradas

    resources :payments

    resources :expenses

    root  'customers#index'

    resources :orders do
        resources :receipts, shallow: true
    end

    resources :line_items do
        get :autocomplete_product_code, :on => :collection
    end

    resources :customers do
        resources :orders, shallow: true
    end
    resources :customers, shallow: true do
        resources :orders do
            resources :line_items, only: [:new, :create, :edit, :update, :destroy, :autocomplete]
        end
    end

    resources :users
    resources :products, controllers: {line_item: 'line_item'}
    resources :sessions, only: [:new, :create, :destroy]
    resources :orders

    get '/signin' => 'sessions#new'
    delete '/signout' => 'sessions#destroy'

    get 'info' => "orders#info", :as => :order_info

end

app/models/payment.rb
class Payment < ActiveRecord::Base
	belongs_to :order
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show, :edit, :update, :destroy]

  # GET /payments
  # GET /payments.json
  def index
    @payments = Payment.all
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(payment_params)
      if @payment.save
        flash[:success] = "Pagamento adicionado com sucesso!"
          redirect_to @payment
      else
          flash[:danger] = "Despesa não foi adicionado!"
        render "new"
      end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
      if @payment.update(payment_params)
        flash[:success] = "Pagamento alterado com sucesso!"
          redirect_to @payment
      else
        flash[:danger] = "Pagamento não foi alterado!"
          render "edit"
      end

  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_params
      params.require(:payment).permit(:form, :date_payment, :date_one_portion, :date_two_portion, :date_three_portion, :date_one_payment, :date_two_payment, :date_three_payment)
    end
end

app/helpers/payment_helper.rb
module PaymentHelper

	
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<%= form_for(@payment) do |p| %>
<% if @payment.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(@payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

    <ul>
        <% @payment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
</div>
<% end %>


<div class="form-group">
    <br>
    <h4>FORMA DE PAGAMENTO:</h4>
    <div class="row">
        <div class="col-md-4">
            <%= p.select :form, options_for_select(type_payment, @payment[:form]), {}, class: "form-control selectFormPayment" %>
        </div>
        <%= render partial: "shared/validation_error_message_first",
locals: { err_msgs: @payment.errors[:form], attr_name: "Forma de Pagamento" }%>
    </div>
</div>

<div class="row">
    <div class="col-lg-6">
        <h4>DATAS DE VENCIMENTO DAS PARCELAS</h4>
        <div class="form-group" id="primParc">
            <label for="">DATA DA 1ª PARC.:</label>
            <div class="row">
                <div class="col-md-6">
                    <%= p.text_field :date_one_portion, id: "datepickerOnePortion", class: "form-control", value: @payment.date_one_portion.try(:strftime, "%-d/%-m/%Y"), placeholder: "Selecione a data" %>
                </div>
            </div>
        </div>
        <div class="form-group" id="segParc">
            <label for="">DATA DA 2ª PARC.:</label>
            <div class="row">
                <div class="col-md-6">
                    <%= p.text_field :date_two_portion, id: "datepickerTwoPortion", class: "form-control", value: @payment.date_two_portion.try(:strftime, "%-d/%-m/%Y"), placeholder: "Selecione a data" %>
                </div>
            </div>
        </div>
        <div class="form-group" id="terParc">
            <label for="">DATA DA 3ª PARC.:</label>
            <div class="row">
                <div class="col-md-6">
                    <%= p.text_field :date_three_portion, id: "datepickerThreePortion", class: "form-control", value: @payment.date_three_portion.try(:strftime, "%-d/%-m/%Y"), placeholder: "Selecione a data" %>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-6">
        <h4>DATAS DE PAGAMENTO DAS PARCELAS</h4>
        <div class="form-group" id="pagAvista">
            <label for="">DATA DO PAGAMENTO:</label>
            <div class="row">
                <div class="col-md-6">
                    <%= p.text_field :date_payment, id: "datepicker", class: "form-control", value: @payment.date_payment.try(:strftime, "%-d/%-m/%Y"), placeholder: "Selecione a data" %>
                </div>
            </div>
        </div>
        <div class="form-group" id="pagPrimParc">
            <label for="">DATA DO PAGAMENTO DA 1ª PARC.:</label>
            <div class="row">
                <div class="col-md-6">
                    <%= p.text_field :date_one_payment, id: "datepickerOnePayment", class: "form-control", value: @payment.date_one_payment.try(:strftime, "%-d/%-m/%Y"), placeholder: "Selecione a data" %>
                </div>
            </div>
        </div>
        <div class="form-group" id="pagSegParc">
            <label for="">DATA DO PAGAMENTO DA 2ª PARC.:</label>
            <div class="row">
                <div class="col-md-6">
                    <%= p.text_field :date_two_payment, id: "datepickerTwoPayment", class: "form-control", value: @payment.date_two_payment.try(:strftime, "%-d/%-m/%Y"), placeholder: "Selecione a data" %>
                </div>
            </div>
        </div>
        <div class="form-group" id="pagTerParc">
            <label for="">DATA DO PAGAMENTO DA 3ª PARC.:</label>
            <div class="row">
                <div class="col-md-6">
                    <%= p.text_field :date_three_payment, id: "datepickerThreePayment", class: "form-control", value: @payment.date_three_payment.try(:strftime, "%-d/%-m/%Y"), placeholder: "Selecione a data" %>
                </div>
            </div>
        </div>
    </div>
</div>



<div class="actions" style="text-align: right">

    <%= link_to 'Voltar', order_path(@payment.order_id), class: "btn btn-default pull-right" %>
    <%= p.submit "Salvar", class: "btn btn-primary pull-right" %>
    <% end %>

</div>
<br><br><br>
<script>
    $(document).ready(function(){

        var init = $('#payment_form').val();

        if (init == 'A vista'){
            
            $('#pagAvista').show();
            $('#primParc').hide();
            $('#segParc').hide();
            $('#terParc').hide();
            $('#pagPrimParc').hide();
            $('#pagSegParc').hide();
            $('#pagTerParc').hide();


        }
        else if (init == '1x Parcela'){
            $('#primParc').show();
            $('#segParc').hide();
            $('#terParc').hide();
            $('#pagPrimParc').show();
            $('#pagSegParc').hide();
            $('#pagTerParc').hide();
            $('#pagAvista').hide();
        }
        else if (init == '2x Parcelas'){
            $('#primParc').show();
            $('#segParc').show();
            $('#terParc').hide();
            $('#pagPrimParc').show();
            $('#pagSegParc').show();
            $('#pagTerParc').hide();
            $('#pagAvista').hide();
        }
        else {
            $('#primParc').show();
            $('#segParc').show();
            $('#terParc').show();
            $('#pagPrimParc').show();
            $('#pagSegParc').show();
            $('#pagTerParc').show();
            $('#pagAvista').hide();

        };


        $('#payment_form').change(function(){

            var value = $('#payment_form').val();
            if (value == 'A vista'){
                $('#pagAvista').show();
                $('#primParc').hide();
                $('#segParc').hide();
                $('#terParc').hide();
                $('#pagPrimParc').hide();
                $('#pagSegParc').hide();
                $('#pagTerParc').hide();
            }
            else if (value == '1x Parcela'){
                $('#primParc').show();
                $('#segParc').hide();
                $('#terParc').hide();
                $('#pagPrimParc').show();
                $('#pagSegParc').hide();
                $('#pagTerParc').hide();
                $('#pagAvista').hide();
            }
            else if (value == '2x Parcelas'){
                $('#primParc').show();
                $('#segParc').show();
                $('#terParc').hide();
                $('#pagPrimParc').show();
                $('#pagSegParc').show();
                $('#pagTerParc').hide();
                $('#pagAvista').hide();
            }
            else {
                $('#primParc').show();
                $('#segParc').show();
                $('#terParc').show();
                $('#pagPrimParc').show();
                $('#pagSegParc').show();
                $('#pagTerParc').show();
                $('#pagAvista').hide();

            };
        });

    });

</script>

app/views/payments/edit.html.erb
<div class="container">
<h1>Editar Pagamento</h1>

<%= render 'form' %>
</div>

app/views/payments/index.html.erb
<h1>Listing payments</h1>

<table>
  <thead>
    <tr>
      <th>Form</th>
      <th>Date payment</th>
      <th>Date one portion</th>
      <th>Date two portion</th>
      <th>Date three portion</th>
      <th>Date one payment</th>
      <th>Date two payment</th>
      <th>Date three payment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= payment.form %></td>
        <td><%= payment.date_payment %></td>
        <td><%= payment.date_one_portion %></td>
        <td><%= payment.date_two_portion %></td>
        <td><%= payment.date_three_portion %></td>
        <td><%= payment.date_one_payment %></td>
        <td><%= payment.date_two_payment %></td>
        <td><%= payment.date_three_payment %></td>
        <td><%= link_to 'Show', payment %></td>
        <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
        <td><%= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment', new_payment_path %>

app/views/payments/new.html.erb
<h1>New payment</h1>

<%= render 'form' %>

<%= link_to 'Back', payments_path %>

app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>
<h1 style="text-align: center">Pagamento</h1>
<table class="table table-striped table-hover">
      <tr>
        <td class="field-label col-md-2 active text-right"><label>NOME:</label></td>
        <td class="col-md-4"><%= @payment.form %></td>
      </tr>
      <tr>
        <td class="field-label col-md-2 active text-right"><label>FORMA DE PAGAMENTO:</label></td>
        <td class="col-md-4"><%= @payment.date_payment.try(:strftime, "%-d/%-m/%Y") %></td>
      </tr>
      <tr>
        <td class="field-label col-md-2 active text-right"><label>DATA DA 1ª PARC.:</label></td>
        <td class="col-md-4"><%= @payment.date_one_portion.try(:strftime, "%-d/%-m/%Y") %></td>
      </tr>
        <tr>
        <td class="field-label col-md-2 active text-right"><label>DATA DO PAGAMENTO DA 1ª PARC.:</label></td>
        <td class="col-md-4"><%= @payment.date_one_payment.try(:strftime, "%-d/%-m/%Y") %></td>
      </tr>
      <tr>
        <td class="field-label col-md-2 active text-right"><label>DATA DA 2ª PARC.:</label></td>
        <td class="col-md-4"><%= @payment.date_two_portion.try(:strftime, "%-d/%-m/%Y") %></td>
      </tr>
      <tr>
        <td class="field-label col-md-2 active text-right"><label>DATA DO PAGAMENTO DA 2ª PARC.:</label></td>
        <td class="col-md-4"><%= @payment.date_two_payment.try(:strftime, "%-d/%-m/%Y") %></td>
      </tr>
      <tr>
        <td class="field-label col-md-2 active text-right"><label>DATA DA 3ª PARC.:</label></td>
        <td class="col-md-4"><%= @payment.date_three_portion.try(:strftime, "%-d/%-m/%Y") %></td>
      </tr>
       <tr>
        <td class="field-label col-md-2 active text-right"><label>DATA DO PAGAMENTO DA 3ª PARC.:</label></td>
        <td class="col-md-4"><%= @payment.date_three_payment.try(:strftime, "%-d/%-m/%Y") %></td>
      </tr>
    </table>
<%= link_to 'Voltar', order_path(@payment.order_id), class: "btn btn-default pull-right" %>
<%= link_to 'Editar', edit_payment_path(@payment), class: "btn btn-warning pull-right" %> 