config/routes.rb
Associations::Application.routes.draw do
    resources :receipts

    resources :entradas

    resources :payments

    resources :expenses

    root  'customers#index'

    resources :orders do
        resources :receipts, shallow: true
    end

    resources :line_items do
        get :autocomplete_product_code, :on => :collection
    end

    resources :customers do
        resources :orders, shallow: true
    end
    resources :customers, shallow: true do
        resources :orders do
            resources :line_items, only: [:new, :create, :edit, :update, :destroy, :autocomplete]
        end
    end

    resources :users
    resources :products, controllers: {line_item: 'line_item'}
    resources :sessions, only: [:new, :create, :destroy]
    resources :orders

    get '/signin' => 'sessions#new'
    delete '/signout' => 'sessions#destroy'

    get 'info' => "orders#info", :as => :order_info

end

app/models/receipt.rb
class Receipt < ActiveRecord::Base
    belongs_to :order




end

app/controllers/receipts_controller.rb
class ReceiptsController < ApplicationController
    before_action :set_receipt, only: [:show, :edit, :update, :destroy]
    before_action :find_order, only: [:new, :create]
    
    # GET /receipts
    # GET /receipts.json
    def index
        @receipts = Receipt.all
    end

    # GET /receipts/1
    # GET /receipts/1.json
    def show
    end

    # GET /receipts/new
    def new
        @receipt = Receipt.new
    end

    # GET /receipts/1/edit
    def edit
    end

    # POST /receipts
    # POST /receipts.json
    def create
        @receipt = @order.receipt.build(receipt_params)
        respond_to do |format|
            if @receipt.save
                format.html { redirect_to @order, notice: 'Receipt was successfully created.' }
                format.json { render action: 'show', status: :created, location: @receipt }
            else
                format.html { render action: 'new' }
                format.json { render json: @receipt.errors, status: :unprocessable_entity }
            end
        end
    end

    # PATCH/PUT /receipts/1
    # PATCH/PUT /receipts/1.json
    def update
        respond_to do |format|
            if @receipt.update(receipt_params)
                format.html { redirect_to @order, notice: 'Receipt was successfully updated.' }
                format.json { head :no_content }
            else
                format.html { render action: 'edit' }
                format.json { render json: @receipt.errors, status: :unprocessable_entity }
            end
        end
    end

    # DELETE /receipts/1
    # DELETE /receipts/1.json
    def destroy
        @order = Order.find(@receipt.order_id)
        @receipt.destroy
        respond_to do |format|
            format.html { redirect_to order_path(@order) }
            format.json { head :no_content }
        end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_receipt
        @receipt = Receipt.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def receipt_params
        params.require(:receipt).permit(:date, :value)
    end
    def find_order
        @order = Order.find(params[:order_id])
    end
    def find_receipt
        @receipt = Receipt.find(params[:id])
    end

end

app/helpers/receipts_helper.rb
module ReceiptsHelper
end

app/views/receipts/_form.html.erb
<%= form_for [@order, @receipt], html: {class: "form-horizontal"} do |f| %>
<% if @receipt.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(@receipt.errors.count, "error") %> prohibited this receipt from being saved:</h2>

    <ul>
        <% @receipt.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
</div>
<% end %>


<div class="form-group">
    <%= f.label "Data:", class: "col-lg-4 control-label" %><br>
    <div class="col-lg-4">
        <%= f.text_field :date, id: "datepicker", class: "form-control",
value: @order.date = DateTime.now.strftime("%-d/%-m/%Y") %>
    </div>
</div>
<div class="form-group">

    <%= f.label "Valor:", class: "col-lg-4 control-label" %><br>

    <div class="col-lg-4">
        <%= f.text_field :value, class: "form-control" %>
    </div>

</div>
<div class="actions">
    <%= link_to 'Voltar', order_path(@order), class: "btn btn-default pull-right" %>
    <%= f.submit "Salvar", class: "btn btn-primary pull-right" %>
</div>
<% end %>

app/views/receipts/edit.html.erb
<h1>Editing receipt</h1>

<%= render 'form' %>

<%= link_to 'Show', @receipt %> |
<%= link_to 'Back', receipts_path %>

app/views/receipts/index.html.erb
<h1>Listing receipts</h1>

<table>
  <thead>
    <tr>
      <th>Order</th>
      <th>Date</th>
      <th>Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @receipts.each do |receipt| %>
      <tr>
        <td><%= receipt.order %></td>
        <td><%= receipt.date %></td>
        <td><%= receipt.value %></td>
        <td><%= link_to 'Show', receipt %></td>
        <td><%= link_to 'Edit', edit_receipt_path(receipt) %></td>
        <td><%= link_to 'Destroy', receipt, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Receipt', new_receipt_path %>

app/views/receipts/new.html.erb
<div class="col-lg-3"></div>
<div class="col-lg-6">
    <h1>Novo Recebimento</h1>

    <%= render 'form' %>

    
</div>

app/views/receipts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Order:</strong>
  <%= @receipt.order %>
</p>

<p>
  <strong>Date:</strong>
  <%= @receipt.date %>
</p>

<p>
  <strong>Value:</strong>
  <%= @receipt.value %>
</p>

<%= link_to 'Edit', edit_receipt_path(@receipt) %> |
<%= link_to 'Back', receipts_path %>